server:
  port: 8084

spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      discovery:
        service-name: ${spring.application.name}
        ip: ${NACOS_DISCOVERY_IP:127.0.0.1}
        port: ${server.port}
      config:
        import-check:
          enabled: false
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        file-extension: yaml
  config:
    import: "optional:nacos:${spring.application.name}.yaml"
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6380} # 根据 docker-compose.yaml 中的 localhost 映射
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://${REDIS_HOST:127.0.0.1}:${REDIS_PORT:6380}"

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml

  snowflake:
    worker-id: 124 # 订单服务的worker id，与商品服务不同以避免冲突

  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  registry:
    type: nacos
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      group: SEATA_GROUP
      namespace: public
  config:
    type: nacos
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      group: SEATA_GROUP
      namespace: public
